# Generated by Django 5.2 on 2025-06-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aeroport', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compagnie', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pays_attache', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.IntegerField()),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('longueur_piste_necessaire', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('longueur', models.IntegerField()),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aeroport')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_avion', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compagnie')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typeavion')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vol', models.IntegerField()),
                ('pilote', models.CharField(max_length=50)),
                ('date_heure_depart', models.DateField()),
                ('date_heure_arrivee', models.DateField()),
                ('aeroport_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee_vols', to='app.aeroport')),
                ('aeroport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_vols', to='app.aeroport')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.avion')),
            ],
        ),
    ]
